// generated by stringer -type=Weekday,Month; DO NOT EDIT

package date

import "fmt"

const _Weekday_name = "MondayTuesdayWednesdayThursdayFridaySaturdaySunday"

var _Weekday_index = [...]uint8{0, 6, 13, 22, 30, 36, 44, 50}

func (i Weekday) String() string {
	i -= 1
	if i < 0 || i+1 >= Weekday(len(_Weekday_index)) {
		return fmt.Sprintf("Weekday(%d)", i+1)
	}
	return _Weekday_name[_Weekday_index[i]:_Weekday_index[i+1]]
}

const _Month_name = "JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember"

var _Month_index = [...]uint8{0, 7, 15, 20, 25, 28, 32, 36, 42, 51, 58, 66, 74}

func (i Month) String() string {
	i -= 1
	if i < 0 || i+1 >= Month(len(_Month_index)) {
		return fmt.Sprintf("Month(%d)", i+1)
	}
	return _Month_name[_Month_index[i]:_Month_index[i+1]]
}
